[package]
org = "ballerinax"
name = "candid"
version = "@toml.version@"
authors = ["Ballerina"]
export = ["candid", "candid.charitycheckpdf", "candid.essentials", "candid.premier"]
keywords = ["Nonprofit Data", "Philanthropy Data", "Nonprofit APIs", "Vendor/Candid", "Area/Other", "Type/Connector"]
repository = "https://github.com/ballerina-platform/module-ballerinax-candid"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.8.0"

[build-options]
observabilityIncluded = true
